language: generic
sudo: required
dist: bionic

services:
  - docker

script:
  - docker build -t riotdocker .
  - docker image ls riotdocker:latest
  - git clone --depth 1 https://github.com/RIOT-OS/RIOT -b 2019.07-branch
  - DOCKER_IMAGE=riotdocker:latest
    BUILD_IN_DOCKER=1
    BOARDS="arduino-uno esp32-wroom-32 hifive1 msb-430h native pic32-wifire samr21-xpro"
    make -CRIOT/examples/hello-world buildtest
  - DOCKER_IMAGE=riotdocker:latest
    TOOLCHAIN=llvm
    BUILD_IN_DOCKER=1
    BOARDS="native samr21-xpro"
    make -CRIOT/examples/hello-world buildtest
