language: generic
dist: bionic
os: linux

services:
  - docker

# settings needed by bors (see https://bors.tech/documentation/getting-started/)
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master

env:
  - RIOT_BRANCH=2021.01-branch

script:
  - docker build -t riot/riotdocker-base riotdocker-base
  - docker build -t riot/static-test-tools static-test-tools
  - docker build --pull -t riotdocker riotbuild 
  - docker image ls riotdocker:latest
  - git clone --depth 1 https://github.com/RIOT-OS/RIOT -b ${RIOT_BRANCH}
  - DOCKER_IMAGE=riotdocker:latest
    BUILD_IN_DOCKER=1
    BOARDS="arduino-uno esp32-wroom-32 hifive1 msb-430h native pic32-wifire samr21-xpro"
    make -CRIOT/examples/hello-world buildtest
  - DOCKER_IMAGE=riotdocker:latest
    TOOLCHAIN=llvm
    BUILD_IN_DOCKER=1
    BOARDS="native samr21-xpro"
    make -CRIOT/examples/hello-world buildtest
  # run static tests
  - docker run --rm -ti -v $(pwd)/RIOT:/data/riotbuild -e CI_BASE_BRANCH=${RIOT_BRANCH} riotdocker:latest ./dist/tools/ci/static_tests.sh
