---
name: build

on:
  push:
    branches:
      - master

jobs:
  build-riotdocker-base:
    name: Build and push images
    runs-on: ubuntu-latest
    env:
      RIOT_BRANCH: '2021.01'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache riotdocker-base layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-base-

      - name: Build and push riotdocker-base
        uses: docker/build-push-action@v2
        with:
          context: ./riotdocker-base
          platforms: linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/riotdocker-base:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/riotdocker-base:${{ env.RIOT_BRANCH }}
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base

      - name: Cache static-test-tools
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-static
          key: ${{ runner.os }}-buildx-static-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-static-

      - name: Build and push static-test-tools
        uses: docker/build-push-action@v2
        with:
          context: ./static-test-tools
          platforms: linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/static-test-tools:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/static-test-tools:${{ env.RIOT_BRANCH }}
          build-args: |
            DOCKERHUB_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}
          cache-from: type=local,src=/tmp/.buildx-cache-static
          cache-to: type=local,dest=/tmp/.buildx-cache-static-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-static
          mv /tmp/.buildx-cache-static-new /tmp/.buildx-cache-static

      - name: Cache riotbuild
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-riotbuild
          key: ${{ runner.os }}-buildx-riotbuild-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-riotbuild-

      - name: set environment variables
        run: |
          echo "RIOTBUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "RIOTBUILD_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "RIOTBUILD_VERSION=$(git describe --always)" >> $GITHUB_ENV

      - name: Build and push riotbuild
        uses: docker/build-push-action@v2
        with:
          context: ./riotbuild
          platforms: linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:${{ env.RIOT_BRANCH }}
          build-args: |
            DOCKERHUB_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}
            RIOTBUILD_BRANCH=${{ env.RIOTBUILD_BRANCH }}
            RIOTBUILD_COMMIT=${{ env.RIOTBUILD_COMMIT }}
            RIOTBUILD_VERSION=${{ env.RIOTBUILD_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache-riotbuild
          cache-to: type=local,dest=/tmp/.buildx-cache-riotbuild-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-riotbuild
          mv /tmp/.buildx-cache-riotbuild-new /tmp/.buildx-cache-riotbuild
