name: build

on:
  push:
    branches: master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push riotdocker-base
        uses: docker/build-push-action@v2
        with:
          context: ./riotdocker-base
          file: ./riotdocker-base/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event.push }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/riotdocker-base:latest

      - name: Build and push static-test-tools
        uses: docker/build-push-action@v2
        with:
          context: ./static-test-tools
          file: ./static-test-tools/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event.push }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/static-test-tools:latest

      - name: Build and push riotbuild
        uses: docker/build-push-action@v2
        with:
          context: ./riotbuild
          file: ./riotbuild/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event.push }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest
